availability:
  Available on-premise: Available on-premise
  available on-premise: Available on-premise
  onprem: Available on-premise
  available: Available on-premise
  Available onprem: Available on-premise
  available onprem: Available on-premise
  Available cloud: Available cloud
  available cloud: Available cloud
  cloud: Available cloud
  Research, Development, or Internal (RDI): Research, Development, or Internal (RDI)
  research, development, or internal (rdi): Research, Development, or Internal (RDI)
  rdi: Research, Development, or Internal (RDI)
  research: Research, Development, or Internal (RDI)
  development: Research, Development, or Internal (RDI)
  internal: Research, Development, or Internal (RDI)
  preview: Preview

columns:
  training:
    "2.0.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      dlrm: ["Benchmark results (minutes)", "Recommendation", "1TB Clickthrough", "DLRM"]
      maskrcnn: ["Benchmark results (minutes)", "Object detection, heavy-weight", "COCO", "Mask R-CNN"]
      minigo: ["Benchmark results (minutes)", "Reinforcement Learning", "Go", "Minigo"]
      resnet: ["Benchmark results (minutes)", "Image classification", "ImageNet", "ResNet"]
      ssd: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      rnnt: ["Benchmark results (minutes)", "Speech recognition", "LibriSpeech", "RNN-T"]
      unet3d: ["Benchmark results (minutes)", "Image segmentation (medical)", "KiTS19", "3D U-Net"]
      default: [" ", " ", " "]
    "2.1.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      dlrm: ["Benchmark results (minutes)", "Recommendation", "1TB Clickthrough", "DLRM"]
      maskrcnn: ["Benchmark results (minutes)", "Object detection, heavy-weight", "COCO", "Mask R-CNN"]
      minigo: ["Benchmark results (minutes)", "Reinforcement Learning", "Go", "Minigo"]
      resnet: ["Benchmark results (minutes)", "Image classification", "ImageNet", "ResNet"]
      ssd: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      rnnt: ["Benchmark results (minutes)", "Speech recognition", "LibriSpeech", "RNN-T"]
      unet3d: ["Benchmark results (minutes)", "Image segmentation (medical)", "KiTS19", "3D U-Net"]
      default: [" ", " ", " "]
    "3.0.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      gpt3: ["Benchmark results (minutes)", "LLM", "C4", "GPT3"]
      dlrm_dcnv2: ["Benchmark results (minutes)", "Recommendation", "1TB Multihot Clickthrough", "DLRM DCNv2"]
      maskrcnn: ["Benchmark results (minutes)", "Object detection, heavy-weight", "COCO", "Mask R-CNN"]
      minigo: ["Benchmark results (minutes)", "Reinforcement Learning", "Go", "Minigo"]
      resnet: ["Benchmark results (minutes)", "Image classification", "ImageNet", "ResNet"]
      ssd: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      rnnt: ["Benchmark results (minutes)", "Speech recognition", "LibriSpeech", "RNN-T"]
      unet3d: ["Benchmark results (minutes)", "Image segmentation (medical)", "KiTS19", "3D U-Net"]
      default: [" ", " ", " "]
    "3.1.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      gpt3: ["Benchmark results (minutes)", "LLM", "C4", "GPT3"]
      dlrm_dcnv2: ["Benchmark results (minutes)", "Recommendation", "1TB Multihot Clickthrough", "DLRM DCNv2"]
      maskrcnn: ["Benchmark results (minutes)", "Object detection, heavy-weight", "COCO", "Mask R-CNN"]
      minigo: ["Benchmark results (minutes)", "Reinforcement Learning", "Go", "Minigo"]
      resnet: ["Benchmark results (minutes)", "Image classification", "ImageNet", "ResNet"]
      ssd: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      rnnt: ["Benchmark results (minutes)", "Speech recognition", "LibriSpeech", "RNN-T"]
      unet3d: ["Benchmark results (minutes)", "Image segmentation (medical)", "KiTS19", "3D U-Net"]
      stable_diffusion: ["Benchmark results (minutes)", "Text to image", "Laion 400m and Coco-2017", "StableDiffusion"]
      default: [" ", " ", " "]
    "4.0.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      gpt3: ["Benchmark results (minutes)", "LLM", "C4", "GPT3"]
      dlrm_dcnv2: ["Benchmark results (minutes)", "Recommendation", "1TB Multihot Clickthrough", "DLRM DCNv2"]
      maskrcnn: ["Benchmark results (minutes)", "Object detection, heavy-weight", "COCO", "Mask R-CNN"]
      minigo: ["Benchmark results (minutes)", "Reinforcement Learning", "Go", "Minigo"]
      resnet: ["Benchmark results (minutes)", "Image classification", "ImageNet", "ResNet"]
      ssd: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      rnnt: ["Benchmark results (minutes)", "Speech recognition", "LibriSpeech", "RNN-T"]
      unet3d: ["Benchmark results (minutes)", "Image segmentation (medical)", "KiTS19", "3D U-Net"]
      stable_diffusion: ["Benchmark results (minutes)", "Text to image", "Laion 400m and Coco-2017", "StableDiffusion"]
      llama2_70b_lora: ["Benchmark results (minutes)", "LLM-Finetune", "SCROLSS Gov Report", "LLama2-70B-LoRA"]
      gnn: ["Benchmark results (minutes)", "Graph node classification", "IGBH-Full", "R-GAT"]
      default: [" ", " ", " "]
    "4.1.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      gpt3: ["Benchmark results (minutes)", "LLM", "C4", "GPT3"]
      dlrm_dcnv2: ["Benchmark results (minutes)", "Recommendation", "1TB Multihot Clickthrough", "DLRM DCNv2"]      
      ssd: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      stable_diffusion: ["Benchmark results (minutes)", "Text to image", "Laion 400m and Coco-2017", "StableDiffusion"]
      llama2_70b_lora: ["Benchmark results (minutes)", "LLM-Finetune", "SCROLSS Gov Report", "LLama2-70B-LoRA"]
      gnn: ["Benchmark results (minutes)", "Graph node classification", "IGBH-Full", "R-GAT"]
      default: [" ", " ", " "]
    "5.0.0":
      bert: ["Benchmark results (minutes)", "NLP", "Wikipedia", "BERT"]
      dlrm_dcnv2: ["Benchmark results (minutes)", "Recommendation", "1TB Multihot Clickthrough", "DLRM DCNv2"]      
      retinanet: ["Benchmark results (minutes)", "Object detection, light-weight", "OpenImages", "RetinaNet"]
      stable_diffusion: ["Benchmark results (minutes)", "Text to image", "Laion 400m and Coco-2017", "StableDiffusion"]
      llama2_70b_lora: ["Benchmark results (minutes)", "LLM-Finetune", "SCROLSS Gov Report", "LLama2-70B-LoRA"]
      rgat: ["Benchmark results (minutes)", "Graph node classification", "IGBH-Full", "R-GAT"]
      default: [" ", " ", " "]

  hpc:
    "2.0.0":
      bert: ["Benchmark results (minutes)", "CosmoFlow"]
      dlrm: ["Benchmark results (minutes)", "DeepCAM"]
      maskrcnn: ["Benchmark results (minutes)", "OpenCatalyst"]
      default: [" "]
